// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShop.Data;

namespace PetShop.Migrations
{
    [DbContext(typeof(PetShopContext))]
    partial class PetShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetShop.Model.Agendamento", b =>
                {
                    b.Property<int>("AgendametoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnimalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AnimalId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Servico")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgendametoId");

                    b.HasIndex("AnimalId1");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("PetShop.Model.Agendamento_servico", b =>
                {
                    b.Property<int>("Agendamento_servicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgendamentoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade_servicos")
                        .HasColumnType("int");

                    b.Property<string>("ServicoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServicoId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Agendamento_servicoId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("ServicoId1");

                    b.ToTable("Agendamento_servico");
                });

            modelBuilder.Entity("PetShop.Model.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agressividade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClienteId1")
                        .HasColumnType("int");

                    b.Property<string>("GeneroAnimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Animal")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RacaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RacaId1")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.HasIndex("ClienteId1");

                    b.HasIndex("RacaId1");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("PetShop.Model.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PetShop.Model.Pagamento", b =>
                {
                    b.Property<int>("PagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClienteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClienteId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor_total")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("PagamentoId");

                    b.HasIndex("ClienteId1");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("PetShop.Model.Raca", b =>
                {
                    b.Property<int>("RacaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais_origem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RacaId");

                    b.ToTable("Racas");
                });

            modelBuilder.Entity("PetShop.Model.Servico", b =>
                {
                    b.Property<int>("ServicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Duracao")
                        .HasColumnType("real");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ServicoId");

                    b.ToTable("Servico");
                });

            modelBuilder.Entity("PetShop.Model.Agendamento", b =>
                {
                    b.HasOne("PetShop.Model.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId1");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PetShop.Model.Agendamento_servico", b =>
                {
                    b.HasOne("PetShop.Model.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId");

                    b.HasOne("PetShop.Model.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId1");

                    b.Navigation("Animal");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("PetShop.Model.Animal", b =>
                {
                    b.HasOne("PetShop.Model.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId1");

                    b.HasOne("PetShop.Model.Raca", "Raca")
                        .WithMany()
                        .HasForeignKey("RacaId1");

                    b.Navigation("Cliente");

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("PetShop.Model.Pagamento", b =>
                {
                    b.HasOne("PetShop.Model.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId1");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
